/**
 * Created by Balaji Thummalapenta on 1/10/16.
 */

export const ACTIONS = {
    ADD_TODO :'ADD_TODO',
    DELETE_TODO :'DELETE_TODO',
    COMPLETE_TODO : 'COMPLETE_TODO',
    SET_VISIBILITY_FILTER :'SET_VISIBILITY_FILTER'
}
export const  VISIBILITY_FILTER = {
    SHOW_ALL: 'SHOW_ALL',
    SHOW_COMPLETED : 'SHOW_COMPLETED',
    SHOW_ACTIVE :'SHOW_ACTIVE'
}

